name: book_hive
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.4.0
  get_it: ^7.3.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  webview_flutter: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf
